### ISSUE TITLE
Help me pleas

### ISSUE THREAD

**Issue by bukarti88** [Scarsz/STEAM-IMG_012#1]
PLeas help me to install it pleas help me you have good project pleas help me to setup itt

**Comment by Scarsz** [comment]
This is a research project to understand how these stealers work, thus I'm not offering support for it.

**Comment by bukarti88** [comment]
pleas show me how to do pleas

**Comment by bukarti88** [comment]
pleas help me

**Comment by Scarsz** [comment]
No.

**Comment by bukarti88** [comment]
how can i learn this then or how much do you want
 o r send me some items from csgo

**Comment by bukarti88** [comment]
pleas help me i will do what do you want

**Comment by Scarsz** [comment]
I'm not helping you; stop asking.
