### ISSUE TITLE
His work has some bugs to fix

### ISSUE THREAD

**Issue by ElPresidentePro** [Scarsz/STEAM-IMG_012#2]
Can not implicitly convert type 'System.IntPtr en'int'.Ya an explicit conversion exists (Check if you need a conversion)

**Comment by Scarsz** [comment]
Once again, this is the decomposed source of Steam stealer; this is on GitHub so people can look at how one of these stealers worked. This is a research project.

**Comment by ElPresidentePro** [comment]
do not care because I've fixed
